## Homework 1: Introduction to Machine Learning for Machine Learning Zoomcamp 2024

In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

#### Question 1. Pandas version (1 point)

In [10]:
pd.__version__

'2.2.2'

In [16]:
import requests

# URL of the file to download
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

# Send a GET request to the URL
response = requests.get(url)

# Open a file in write mode and save the content
with open("laptops.csv", "wb") as file:
    file.write(response.content)  # Write the content to the file

# Now the file 'laptops.csv' is downloaded and saved in the current directory

In [22]:
#df = pd.read_csv("data/data.csv") 
df = pd.read_csv("laptops.csv")

In [24]:
df.head(10)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
5,MSI Crosshair 17 C12VF-264XES Intel Core i7-12...,New,MSI,Crosshair,Intel Core i7,32,1000,SSD,RTX 4060,17.3,No,1699.00
6,Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8G...,New,Lenovo,ThinkPad,AMD Ryzen 5,8,256,SSD,NaN,14.0,No,909.00
7,ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-...,New,Asus,VivoBook,Intel Core i7,8,512,SSD,NaN,15.6,No,809.01
8,Medion Akoya E15415 Intel Core i5-10210U/8GB/2...,New,Medion,Akoya,Intel Core i5,8,256,SSD,NaN,15.6,No,519.00
9,HP Victus 16-d1038ns Intel Core i7-12700H/16GB...,New,HP,Victus,Intel Core i7,16,512,SSD,RTX 3050,16.1,No,1149.00

#### Question 2. Records count (1 point)

In [29]:
#Count records using shape
num_records_shape = df.shape[0]  # The first element is the number of rows

# Count records using len()
num_records_len = len(df)  # This also gives the number of rows

# Print the counts
print("Number of records using shape:", num_records_shape)
print("Number of records using len():", num_records_len)

Number of records using shape: 2160
Number of records using len(): 2160

#### Question 3. Laptop brands (1 point)

In [44]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [46]:
df['Brand'].unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [50]:
df['Brand'].value_counts()

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [52]:
pd.Series(df['Brand'].unique()).value_counts()

Asus                1
Microsoft           1
Realme              1
Millenium           1
Jetwing             1
Innjoo              1
Vant                1
Deep Gaming         1
Denver              1
Thomson             1
Dynabook Toshiba    1
Prixton             1
Primux              1
PcCom               1
Alurin              1
Samsung             1
LG                  1
Dell                1
Gigabyte            1
Razer               1
Apple               1
Acer                1
Medion              1
Lenovo              1
HP                  1
MSI                 1
Toshiba             1
Name: count, dtype: int64

#### Question 4. Missing values (1 point)

In [57]:
# Count missing values in each column
missing_values = df.isnull().sum()
print(missing_values)

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

#### Question 5. Maximum final price (1 point)

In [61]:
df['Final Price'].max()

7150.47

In [64]:
df.describe()

               RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

#### Question 6. Median value of Screen (1 point)

In [68]:
df['Screen'].median()

15.6

#### Question 7. Sum of weights (1 point)